name: welt
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - cairo=1.18.0
  - pango=1.52.1
  - cmake=4.1.2
  - glib=2.80.0
  - libglib=2.80.0
  - gobject-introspection=1.80.1
  - xorg-libxau=1.0.9
